server:
  port: 8761
spring:
  application:
    name: eureka-server01
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#    register-with-eureka: false
  instance:
    metadata-map:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#关闭自我保护机制，保证不可用的服务及时被踢掉
  server:
    enable-self-preservation: false
