
server:
  port: 9090
spring:
  application:
    name: steam-app-01
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring_cloud_test
    username: root
    password: asdasd
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    appname: ${spring.application.name}


mybatis:
  mapper-locations: classpath:mapper/*.xml
